# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_rnd_down <- function(x, granularity) {
    .Call('ppR_fast_rnd_down', PACKAGE = 'ppR', x, granularity)
}

fast_rnd_up <- function(x, granularity) {
    .Call('ppR_fast_rnd_up', PACKAGE = 'ppR', x, granularity)
}

fast_traverse_totals <- function(x, w, buffer, window) {
    .Call('ppR_fast_traverse_totals', PACKAGE = 'ppR', x, w, buffer, window)
}

fast_wtd_mean <- function(x, w) {
    .Call('ppR_fast_wtd_mean', PACKAGE = 'ppR', x, w)
}

